name: Run CWL workflow
        

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cwltool

    - name: Install Python packages
      run: pip install pandas

    - name: Run CWL workflow
      run: |
        cwltool $GITHUB_WORKSPACE/extract_pubid.cwl $GITHUB_WORKSPACE/input.yaml
